// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cwlevpwwpsvqkanljavu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3bGV2cHd3cHN2cWthbmxqYXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjk1NTIsImV4cCI6MjA3NDc0NTU1Mn0.j_ZR3cgqi_TL8UOxBlsJDPH1k1aZZ5selVZqkDH1m0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);